// <auto-generated />
namespace TheWeddingOf.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Attempt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Attempt));
        
        string IMigrationMetadata.Id
        {
            get { return "202001010324103_Attempt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
